"""initial

Revision ID: a328569384f9
Revises: 
Create Date: 2026-04-17 21:51:12.463464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a328569384f9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bilateral_trade',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country_a', sa.String(length=3), nullable=False),
    sa.Column('country_b', sa.String(length=3), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('exports_a_to_b', sa.Float(), nullable=False),
    sa.Column('exports_b_to_a', sa.Float(), nullable=False),
    sa.Column('total_bilateral', sa.Float(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('country_a < country_b'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_a', 'country_b', 'period')
    )
    op.create_table('countries',
    sa.Column('iso3', sa.String(length=3), nullable=False),
    sa.Column('iso2', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('iso3')
    )
    op.create_table('flight_connectivity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country_a', sa.String(length=3), nullable=False),
    sa.Column('country_b', sa.String(length=3), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('route_count', sa.Integer(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('country_a < country_b'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_a', 'country_b', 'period')
    )
    op.create_table('geopolitics_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country_a', sa.String(length=3), nullable=False),
    sa.Column('country_b', sa.String(length=3), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('avg_goldstein', sa.Float(), nullable=False),
    sa.Column('cooperative_ratio', sa.Float(), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('country_a < country_b'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_a', 'country_b', 'period')
    )
    op.create_table('index_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country_a', sa.String(length=3), nullable=False),
    sa.Column('country_b', sa.String(length=3), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('trade_raw', sa.Float(), nullable=True),
    sa.Column('trade_normalized', sa.Float(), nullable=True),
    sa.Column('travel_raw', sa.Float(), nullable=True),
    sa.Column('travel_normalized', sa.Float(), nullable=True),
    sa.Column('geopolitics_raw', sa.Float(), nullable=True),
    sa.Column('geopolitics_normalized', sa.Float(), nullable=True),
    sa.Column('composite_score', sa.Float(), nullable=False),
    sa.Column('coverage', sa.String(length=50), nullable=False),
    sa.Column('computed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('country_a < country_b'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_a', 'country_b', 'period')
    )
    op.create_table('narrative_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country_a', sa.String(length=3), nullable=False),
    sa.Column('country_b', sa.String(length=3), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('narrative_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quality_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_period', sa.String(length=10), nullable=False),
    sa.Column('findings', sa.JSON(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visitor_flows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('origin', sa.String(length=3), nullable=False),
    sa.Column('destination', sa.String(length=3), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('visitor_count', sa.Integer(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('origin', 'destination', 'period')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visitor_flows')
    op.drop_table('quality_reports')
    op.drop_table('narrative_reports')
    op.drop_table('index_snapshots')
    op.drop_table('geopolitics_scores')
    op.drop_table('flight_connectivity')
    op.drop_table('countries')
    op.drop_table('bilateral_trade')
    # ### end Alembic commands ###
