"""add trade_log to index_snapshots

Revision ID: c38ef2975cfe
Revises: cf40e76665ab
Create Date: 2026-04-21 10:55:24.928366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c38ef2975cfe'
down_revision: Union[str, None] = 'cf40e76665ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('index_snapshots', sa.Column('trade_log', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('index_snapshots', 'trade_log')
    # ### end Alembic commands ###
