"""add goldstein and cooperative_ratio to index_snapshots

Revision ID: cf40e76665ab
Revises: a328569384f9
Create Date: 2026-04-21 10:41:12.056776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf40e76665ab'
down_revision: Union[str, None] = 'a328569384f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('index_snapshots', sa.Column('avg_goldstein', sa.Float(), nullable=True))
    op.add_column('index_snapshots', sa.Column('cooperative_ratio', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('index_snapshots', 'cooperative_ratio')
    op.drop_column('index_snapshots', 'avg_goldstein')
    # ### end Alembic commands ###
