"""add geopolitics_event_count to index_snapshots

Revision ID: d7c76914dbac
Revises: 20c3ebf06909
Create Date: 2026-04-21 11:17:06.340929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7c76914dbac'
down_revision: Union[str, None] = '20c3ebf06909'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('index_snapshots', sa.Column('geopolitics_event_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('index_snapshots', 'geopolitics_event_count')
    # ### end Alembic commands ###
